config/routes.rb
Rails.application.routes.draw do
  root 'regions#index'

  devise_for :users

  resources :users, only: :show do
    resources :itineraries, only: [:index, :show, :new, :create]
  end

  # resources :itineraries, only: [:index, :show, :new, :create]

  resources :regions, only: [:index, :show] do
    resources :cities, only: [:index, :show]
  end

resources :excursions, only: :show



  resources :categories, only: :index

  resources :cities, only: :index

  resources :cities, only: :show do
    resources :excursions, only: :show
  end



  namespace :api do
    namespace :v1 do
      resources :cities, only: [:show] do
        post "/excursions", to: "excursions#search"
        get "/excursions", to: "excursions#business"
        get "/businesses", to: "businesses#search"
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :create, :new, :show, :update, :destroy]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :itineraries, only: [:create, :index, :show, :destroy] do
        resources :events, only: [:index, :show, :update]
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: [:index, :show]
      resources :locations, only: :index
  end
end

namespace :api do
  namespace :v1 do
      post "/queries", to: "queries#search"
  end
end


end

app/models/region.rb
class Region < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :cities
  # has_many :excursions
end

app/controllers/api/v1/regions_controller.rb
class Api::V1::RegionsController < Api::V1::ApiController

def index
  render json: Region.all
end

def show
  render json: Region.find(params[:id])
end

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
    @regions = Region.all
  end

  def show
    @region = Region.find(params[:id])
    @cities = @region.cities
  end
end

app/views/regions/index.html.erb
<div class="row">
<div class="index-search-form">
  <div id="app">
  </div>
  </div>
  </div>


<div class="region-index-page">
<h2 class="region-index-heading"> Browse by Region </h2>
<%@regions.each do |region|%>
<%=link_to region_path(region) do%>
<div class="region">
  <div class="region-index-tile small-4 columns">
    <div class="hvrbox">
      <img src= "<%=region.image%>" class="hvrbox-layer_bottom region-picture"/>
      <div class="hvrbox-layer_top">
        <div class="hvrbox-text">
          <h3 class="region-name">
            <%=region.name%>
          </h3>
        </div>
      </div>
    </div>
  </div>
</div>
<%end%>
<%end%>
</div>

app/views/regions/show.html.erb
<div class="region-index-page">
<h2 class="region-index-heading"><%=@region.name%></h2>
<%@cities.each do |city|%>
<div class="region">
  <div class="city-index-tile small-3 columns">
    <div class="hvrbox">
      <img src= "<%=city.image%>" class="hvrbox-layer_bottom city-picture"/>
      <div class="hvrbox-layer_top">
        <div class="hvrbox-text">
          <h3 class="region-name">
            <%= link_to city.name, city_path(city), style: "color: white;"%>
          </h3>
        </div>
      </div>
    </div>
  </div>
</div>
<%end%>
</div>